### ISSUE TITLE
predict3d can fail when the response is not a simple variable

### ISSUE THREAD

**Issue by BillVenables** [cardiomoon/predict3d#1]
If the left hand side of the formula is not a simple name predict3d can fail.  Example:

suppressPackageStartupMessages(library(predict3d))

mtcars <- within(mtcars, {
  engine <- ifelse(vs == 0, "V-shaped", "straight")
  gpm <- 100/mpg
})

fit <- lm(100/mpg ~ wt*engine, data = mtcars)
predict3d(fit, radius = 0.125)   ## fails in the final part

fit <- lm(gpm ~ wt*engine, data = mtcars)
predict3d(fit, radius = 0.125)  ## seems to work OK.

**Comment by cardiomoon** [comment]
Please install the developmental version of predict3d from GitHub.
devtools::install_githb("cardiomoon/predict3d")
