### ISSUE TITLE
3D Plotting an interactive multivariate linear regression model in 

### ISSUE THREAD

**Issue by Saadi4469** [cardiomoon/predict3d#5]
Hello,

I am trying to produce a 3D interactive plot for a multivariate linear regression model based this data ()https://app.box.com/s/lxr1iol1t2d8cqnjsfnv1ir2s7uqpi1x. Below is what I have done so far. But the plot is not what I expected. Below is what I have done so far, and the resulting 3D plot doesn't make sense to me. How can I produce a 3D interactive plot based on this model? Hope this makes sense.

```
library(predict3d)
    
    Model = lm(formula = SWE ~ Mean.Z + Intensity.mean, data = df.mean.swe)
    
    predict3d(Model, radius = 0.5)
```

https://imgur.com/oUC4eEO

**Comment by cardiomoon** [comment]
Please try and compare 
```
library(tidyverse)
library(predict3d)
library(ggplot2)

data=read_csv("~/Downloads/df_mean_swe.csv")
ggplot(data,aes(x=Mean.Z,y=SWE))+geom_point()+stat_smooth()
fit = loess(formula = SWE ~ Mean.Z, data = data)
ggPredict(fit,method="loess")
ggplot(data,aes(x=Mean.Z,y=SWE))+geom_point()+stat_smooth(method="lm")
fit = lm(formula = SWE ~ Mean.Z, data = data)
ggPredict(fit,method="loess")
fit = lm(formula = SWE ~ Mean.Z + Intensity.mean, data = data)
summary(data)
ggPredict(fit)
predict3d(fit,radius=200)
```
